GET http://localhost:3000/api/v1/workouts HTTP/1.1

###

GET http://localhost:3000/api/v1/workouts/f4e6a29b-adb3-4924-8ecf-48a844686803 HTTP/1.1

###

POST http://localhost:3000/api/v1/workouts HTTP/1.1
Content-Type: application/json

{
  "name": "Hello World",
  "mode": "AMRAP 20",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ],
  "exercises": [
    "15 toes to bars",
    "10 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}

###

PATCH http://localhost:3000/api/v1/workouts/f4e6a29b-adb3-4924-8ecf-48a844686803 HTTP/1.1
Content-Type: application/json

{
  "exercises": [
    "nothing",
    "sleep",
    "play videogames"
  ]
}

###

DELETE http://localhost:3000/api/v1/workouts/f4e6a29b-adb3-4924-8ecf-48a844686803 HTTP/1.1