GET http://localhost:3000/api/v1/workouts HTTP/1.1

###

GET http://localhost:3000/api/v1/workouts/83808181-05e2-4f13-b7ee-4fe451405ef4   HTTP/1.1

###

POST http://localhost:3000/api/v1/workouts HTTP/1.1
Content-Type: application/json

{
  "name": "Hello World 1",
  "mode": "AMRAP 20",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ],
  "exercises": [
    "15 toes to bars",
    "10 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}

###

PATCH http://localhost:3000/api/v1/workouts/b06effdb-4dd4-4b86-87b9-58ac4a0de502 HTTP/1.1
Content-Type: application/json

{
  "exercises": [
    "nothing",
    "sleep",
    "play videogames"
  ]
}

###

DELETE http://localhost:3000/api/v1/workouts/39c5927f-3cab-41ac-b13c-f4281cd078a8 HTTP/1.1