GET http://localhost:3000/api/v1/workouts HTTP/1.1

###

GET http://localhost:3000/api/v1/workouts/61dbae02-c147-4e28-863c-db7bd402b2d6   HTTP/1.1

###

POST http://localhost:3000/api/v1/workouts HTTP/1.1
Content-Type: application/json

{
  "name": "Hello World 1",
  "mode": "AMRAP 20",
  "equipment": [
    "rack",
    "barbell",
    "abmat"
  ],
  "exercises": [
    "15 toes to bars",
    "10 thrusters",
    "30 abmat sit-ups"
  ],
  "trainerTips": [
    "Split your toes to bars into two sets maximum",
    "Go unbroken on the thrusters",
    "Take the abmat sit-ups as a chance to normalize your breath"
  ]
}

###

PATCH http://localhost:3000/api/v1/workouts/b06effdb-4dd4-4b86-87b9-58ac4a0de502 HTTP/1.1
Content-Type: application/json

{
  "exercises": [
    "nothing",
    "sleep",
    "play videogames"
  ]
}

###

DELETE http://localhost:3000/api/v1/workouts/5e38caf1-59c2-4f13-909d-58f7abb7d5dc HTTP/1.1